### ISSUE TITLE
Please put a readme in the repository

### ISSUE THREAD

**Issue by ddaygold** [Mellanox/mlxsw#1]
I think it would be helpful if the repository had a readme pointing people to the wiki.

I was confused when I clicked through, even though I've used the previous wiki repo.
It's very strange to be greeted with the "This repository is empty" message.

I'd send a pull request, but I can't fork until the repo is non-empty.

**Comment by idosch** [comment]
Hi,

Added a link to the Wiki in README.md

Thanks, Ido.
