### ISSUE TITLE
README in releases at http://switchdev.mellanox.com/releases/ contain wrong wiki URL

### ISSUE THREAD

**Issue by andir** [Mellanox/mlxsw#2]
The releases available at http://switchdev.mellanox.com/releases/ ship a README file which directs to @idosch's `mlxsw` wiki which no long exists. That link should probably be update to point to this repo.

This is content right now:
```
For installation instructions please refer to:

https://github.com/idosch/mlxsw/wiki/Installation
```

**Comment by idosch** [comment]
Thanks, but which release are you using? I just tested mlxsw_FED25-stable.tar.gz and its MOTD is pointing to the correct place.

I'll remove the 4.7 and 4.8 based releases, as they're old. Will upload a Fedora 26 based release later this week after Fedora 26 is gold.

Closing for now. Please re-open if something isn't clear.

Thanks.

**Comment by andir** [comment]
I was using `mlxsw-UBUNTU1704.tar.gz`

**Comment by idosch** [comment]
OK. I'll make sure it's updated. Will close when the fixed image is available.

Thanks

**Comment by idosch** [comment]
Fixed.

Thanks
